# Generated by Django 4.2.9 on 2024-01-16 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_appointment_date_post_news_category_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 16, 16, 11, 5, 343465)),
        ),
    ]
