# Generated by Django 4.2.9 on 2024-01-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_author_category_comment_post_postcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
    ]
